#!/usr/bin/env bash
#
# run-probe.sh — the executable half of loomwright/docs/SPIKES/CROSS_PLUGIN_RESOLUTION.md
#
# Measures three cross-plugin resolution unknowns against a live Claude Code install by
# generating TWO throwaway plugins, registering them through a throwaway marketplace at
# --scope local, observing each unknown from a FRESH `claude -p` process, and tearing the
# whole thing down on every exit path.
#
#   Unknown A — does an agent's `skills:` frontmatter preload resolve ACROSS plugins?
#   Unknown B — what does ${CLAUDE_PLUGIN_ROOT} resolve to inside a SECOND plugin's hooks.json?
#   Unknown C — does Task(subagent_type: "<other-plugin>:<agent>") resolve from a loomwright surface?
#
# Re-run (from the repo root):
#
#     bash loomwright/docs/SPIKES/cross-plugin-probe/run-probe.sh
#
# Everything under transcripts/ is REGENERATED by a run. Diff the result against the
# committed copies to see whether Claude Code's behaviour has changed since the recorded
# measurement.
#
# ---------------------------------------------------------------------------------------
# DESIGN CONSTRAINTS (each exists because of a specific, recorded failure mode)
#
# 1. NO TRACKED FILE IS MUTATED. The nonce lives in a plugin this script authors, so
#    mutation-target == preload-source holds by construction. A nonce written into this
#    repo's own loomwright/skills/ could never reach the *installed* body (a separate
#    snapshot under ~/.claude/plugins/cache/), so that design's only reachable outcome is
#    a false DOES NOT RESOLVE.
# 2. --scope local ONLY. Never `user` (machine-global), never `project` (would write
#    .claude/settings.json into the repo and leak into a PR). `.claude/settings.local.json`
#    is backed up byte-for-byte and restored at teardown.
# 3. NO PERMISSION-BYPASS FLAGS. --dangerously-skip-permissions and
#    --permission-mode bypassPermissions are a standing project prohibition; unused here.
# 4. BOUNDED WAIT ON EVERY NESTED `claude` CALL — probes, installs, AND teardown. Stock
#    macOS has no `timeout(1)`, and a nested headless `claude` can hang on a permission
#    prompt with no TTY (this repo has a recorded wedge from exactly that shape). Every
#    nested call runs in the background and is collected through a FIFO using
#    `IFS= read -r -d '' -t N`. On deadline expiry the step is recorded as UNMEASURED,
#    naming the timeout as the blocker, and the run CONTINUES to teardown.
# 5. HEADLESS `claude` MUST USE -p. Plain `claude` and `claude --agent X` are
#    interactive-by-default and hang without a TTY.
# 6. TOOL ISOLATION AT BOTH LEVELS. The probe agents are declared with no filesystem-read
#    capability, and the observing parent session runs with $PARENT_TOOLS so the parent
#    cannot read the sentinel off disk and relay it either. Without this a false RESOLVES
#    is possible — the sentinel would prove only that *something* in the process tree could
#    read a file.
#
#    "No tools at all" is NOT an available isolation setting, and the residual tool was
#    chosen by measurement rather than taste. Two earlier runs of this probe established:
#      run 1, every tool subtracted -> "would be spawned with zero tools — refusing"
#      run 2, only TaskOutput left  -> "not available to subagents [TaskOutput]"
#    So the agent's resolved tool list must be non-empty AND must contain something that is
#    both subagent-eligible and present in the observing session. `WebSearch` is the weakest
#    tool meeting all three conditions, and it cannot read the local filesystem, so it opens
#    no channel to the sentinel. The zero-tools refusal is preserved as a deliberate control
#    arm (`probe-zero-tools-agent`) rather than discarded.
# ---------------------------------------------------------------------------------------

set -uo pipefail
# Deliberately NOT `set -e`: a failed probe is a RESULT to record, not a reason to abort,
# and teardown must run on every path.

# ---------------------------------------------------------------------------------------
# Paths and identifiers
# ---------------------------------------------------------------------------------------

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../../../.." && pwd)"
TRANSCRIPTS="$HERE/transcripts"
mkdir -p "$TRANSCRIPTS"

PROBE_DATE="${PROBE_DATE:-$(date +%Y-%m-%d)}"
LOG_A="$TRANSCRIPTS/${PROBE_DATE}-unknown-a.log"
LOG_B="$TRANSCRIPTS/${PROBE_DATE}-unknown-b.log"
LOG_C="$TRANSCRIPTS/${PROBE_DATE}-unknown-c.log"
LOG_T="$TRANSCRIPTS/${PROBE_DATE}-teardown.log"

# Deadlines (seconds). Override with PROBE_DEADLINE / PROBE_CLI_DEADLINE.
DEADLINE="${PROBE_DEADLINE:-300}"          # a nested `claude -p` model turn
CLI_DEADLINE="${PROBE_CLI_DEADLINE:-120}"  # a non-model `claude plugin ...` subcommand

MARKET_NAME="xplugin-probe"
HOST_PLUGIN="probe-host"
CONSUMER_PLUGIN="probe-consumer"

# Run-scoped nonce. Regenerated every run, so a stale copy can never satisfy the assertion.
NONCE="XPLUGIN-NONCE-$(date +%s)-${RANDOM}${RANDOM}"

# The pre-existing marker phrase asserted by Unknown A's read-only corroboration arm.
# Chosen for DISTINCTIVENESS, not convenience. The generic checklist lines in
# quality-checklist ("Test coverage >= 80%", "No secrets/PII in code or logs") are
# boilerplate a tool-isolated agent could emit from prior knowledge with no preload at
# all — a false RESOLVES through a channel tool isolation does not close. This phrase is a
# Loomwright coinage, and Phase 0 verifies it is unique within the installed body.
MARKER='Token budget estimated (Context7 needed?)'

# Tool set handed to the OBSERVING parent session, and the single source of truth for both
# the executed command and the command echoed into the transcript — a hand-written echo
# that drifts from the real invocation is exactly the kind of misleading evidence this
# spike exists to avoid.
#
# `Task` is needed to spawn at all. `WebSearch` is the residual tool the probe agents keep,
# and it is chosen by MEASUREMENT, not taste:
#   - subtracting every tool  -> "would be spawned with zero tools - refusing" (run 1)
#   - leaving only TaskOutput -> "not available to subagents [TaskOutput]"     (run 2)
# WebSearch is recognized, is available to subagents, and cannot read the local filesystem,
# so it keeps preload as the only channel to the sentinel.
PARENT_TOOLS="Task,WebSearch"

SCRATCH="${TMPDIR:-/tmp}/loomwright-xplugin-probe-$$"
MARKET_DIR="$SCRATCH/marketplace"
OUT_DIR="$SCRATCH/out"

LOCAL_SETTINGS="$REPO_ROOT/.claude/settings.local.json"
SETTINGS_BACKUP="$SCRATCH/settings.local.json.probe-backup"
SETTINGS_EXISTED="unknown"

banner() { echo; echo "==================== $* ===================="; echo; }

# count_matches <file> <fixed-pattern>
#   `grep -c` prints 0 AND exits 1 on no-match, so the common `grep -c ... || echo 0`
#   idiom emits TWO lines ("0" then "0") and corrupts the evidence. This wrapper keeps
#   grep's single line and swallows only the status.
count_matches() {
  local f="$1" pat="$2"
  if [ -f "$f" ]; then
    grep -cF -- "$pat" "$f" 2>/dev/null || true
  else
    echo "(no such file: $f)"
  fi
}

# ---------------------------------------------------------------------------------------
# Bounded execution (there is no `timeout(1)` on stock macOS)
# ---------------------------------------------------------------------------------------

# run_bounded <label> <deadline_seconds> <cmd...>
#   Runs <cmd...> in the background with stdout+stderr captured to $SCRATCH/<label>.out
#   and collects its exit status through a FIFO with a hard deadline.
#   Returns the command's status, or 124 on deadline expiry.
#
#   The FIFO is opened READ-WRITE (`exec 9<>`) on purpose: a plain `read ... < fifo`
#   blocks in open(2) until a writer appears, which happens only when the command has
#   ALREADY finished — so `read -t` would never get to arm its timeout and the bound
#   would be silently vacuous.
run_bounded() {
  local label="$1" deadline="$2"; shift 2
  local out="$SCRATCH/$label.out" fifo="$SCRATCH/$label.fifo"
  rm -f "$fifo" "$out"; mkfifo "$fifo" || return 125
  ( "$@" >"$out" 2>&1; printf '%s\0' "$?" >"$fifo" ) &
  local bg=$!
  exec 9<>"$fifo"
  local rc=""
  if IFS= read -r -d '' -t "$deadline" rc <&9; then
    exec 9>&-; rm -f "$fifo"
    return "$rc"
  fi
  exec 9>&-; rm -f "$fifo"
  # Kill the CHILDREN first: the subshell `exec`s into `claude`, so claude is its direct
  # child. Killing the subshell first would reparent claude to init and put it out of
  # reach of `pkill -P`.
  pkill -P "$bg" 2>/dev/null
  kill -TERM "$bg" 2>/dev/null
  return 124
}

# emit_capture <label> <status> [deadline]
emit_capture() {
  local label="$1" st="$2" dl="${3:-$DEADLINE}"
  echo "--- exit status: $st ---"
  if [ "$st" = "124" ]; then
    echo "--- UNMEASURED: this step exceeded its ${dl}s bounded-wait deadline and was terminated."
    echo "--- blocker: bounded-wait deadline expiry (see run_bounded; macOS has no timeout(1))."
    echo "--- The run continues to teardown rather than stalling; the verdict for anything"
    echo "--- depending on this step is UNMEASURED, never an inferred yes/no."
  fi
  echo "--- captured stdout+stderr (verbatim) ---"
  cat "$SCRATCH/$label.out" 2>/dev/null || echo "(no capture file)"
  echo "--- end capture ---"
}

# step <label> <deadline> <cmd...> — echo the command, run it bounded, print the capture.
step() {
  local label="$1" dl="$2"; shift 2
  echo "\$ $*"
  run_bounded "$label" "$dl" "$@"
  local st=$?
  emit_capture "$label" "$st" "$dl"
  return $st
}

# claude_bounded <label> <promptfile> [claude args...]
#   The prompt is fed on STDIN, never as a positional argument: `--tools` is variadic and
#   swallows a trailing positional prompt, which fails with
#   "Input must be provided either through stdin or as a prompt argument when using --print".
claude_bounded() {
  local label="$1" pf="$2"; shift 2
  run_bounded "$label" "$DEADLINE" bash -c 'exec claude -p "$@" < "$0"' "$pf" "$@"
}

# ---------------------------------------------------------------------------------------
# Teardown — trap-based, so it runs on success, failure, and interrupt alike
# ---------------------------------------------------------------------------------------

TEARDOWN_DONE=0
teardown() {
  [ "$TEARDOWN_DONE" = "1" ] && return 0
  TEARDOWN_DONE=1
  {
    banner "TEARDOWN  ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
    echo "Runs from an EXIT/INT/TERM trap, so a crash or a Ctrl-C tears down too."
    echo "Every command below is bounded (${CLI_DEADLINE}s) — a teardown that hangs is a"
    echo "teardown that does not happen."
    echo

    step td-uninstall-consumer "$CLI_DEADLINE" \
      claude plugin uninstall "$CONSUMER_PLUGIN" --scope local -y
    step td-uninstall-host "$CLI_DEADLINE" \
      claude plugin uninstall "$HOST_PLUGIN" --scope local -y
    # No --scope: removes the declaration from EVERY scope. Safe, because this marketplace
    # name is created by this script and exists nowhere else.
    step td-market-remove "$CLI_DEADLINE" \
      claude plugin marketplace remove "$MARKET_NAME"

    banner "TEARDOWN ASSERTIONS (raw output)"
    step td-plugin-list "$CLI_DEADLINE" claude plugin list
    cp "$SCRATCH/td-plugin-list.out" "$SCRATCH/final-plugin-list.txt" 2>/dev/null
    step td-market-list "$CLI_DEADLINE" claude plugin marketplace list
    cp "$SCRATCH/td-market-list.out" "$SCRATCH/final-marketplace-list.txt" 2>/dev/null

    echo
    if grep -qF "$HOST_PLUGIN" "$SCRATCH/final-plugin-list.txt" 2>/dev/null
      then echo "ASSERT probe-host absent from plugin list ......... FAIL (still present)"
      else echo "ASSERT probe-host absent from plugin list ......... PASS"; fi
    if grep -qF "$CONSUMER_PLUGIN" "$SCRATCH/final-plugin-list.txt" 2>/dev/null
      then echo "ASSERT probe-consumer absent from plugin list ..... FAIL (still present)"
      else echo "ASSERT probe-consumer absent from plugin list ..... PASS"; fi
    if grep -qF "$MARKET_NAME" "$SCRATCH/final-marketplace-list.txt" 2>/dev/null
      then echo "ASSERT $MARKET_NAME absent from marketplace list .. FAIL (still present)"
      else echo "ASSERT $MARKET_NAME absent from marketplace list .. PASS"; fi

    # The run must not leave behind a loomwright registration it did not inherit.
    local before after
    before="$(count_matches "$SCRATCH/baseline-plugin-list.txt" loomwright)"
    after="$(count_matches "$SCRATCH/final-plugin-list.txt" loomwright)"
    if [ "$before" = "$after" ]
      then echo "ASSERT loomwright registrations unchanged ......... baseline=$before final=$after PASS"
      else echo "ASSERT loomwright registrations unchanged ......... baseline=$before final=$after FAIL"; fi
    echo "  baseline loomwright lines:"; grep 'loomwright' "$SCRATCH/baseline-plugin-list.txt" 2>/dev/null | sed 's/^/    /'
    echo "  final    loomwright lines:"; grep 'loomwright' "$SCRATCH/final-plugin-list.txt" 2>/dev/null | sed 's/^/    /'

    banner "LOCAL SETTINGS RESTORE"
    echo "target: $LOCAL_SETTINGS"
    echo "(gitignored via .gitignore '.claude/*' — verified before the run; this is why"
    echo " --scope local cannot leak into a PR, and why --scope project was forbidden)"
    echo "state before the run: $SETTINGS_EXISTED"
    local restore_ok=1
    if [ "$SETTINGS_EXISTED" = "present" ]; then
      if cp "$SETTINGS_BACKUP" "$LOCAL_SETTINGS" 2>/dev/null && cmp -s "$SETTINGS_BACKUP" "$LOCAL_SETTINGS"; then
        echo "restored byte-for-byte from backup"
        echo "ASSERT settings.local.json identical to pre-run backup ... PASS"
      else
        restore_ok=0
        echo "ASSERT settings.local.json identical to pre-run backup ... FAIL"
        echo "backup preserved at $SETTINGS_BACKUP (scratch is NOT removed below)"
      fi
    elif [ "$SETTINGS_EXISTED" = "absent" ]; then
      rm -f "$LOCAL_SETTINGS"
      if [ -e "$LOCAL_SETTINGS" ]
        then restore_ok=0; echo "ASSERT settings.local.json absent again ... FAIL"
        else echo "deleted (the file did not exist before the run)"; echo "ASSERT settings.local.json absent again ... PASS"; fi
    else
      echo "state was never captured (teardown fired before preflight) — left untouched"
    fi

    banner "REPO CLEANLINESS"
    echo "\$ git -C \$REPO_ROOT status --porcelain -- .claude .claude-plugin loomwright/skills loomwright/agents loomwright/commands loomwright/hooks"
    git -C "$REPO_ROOT" status --porcelain -- .claude .claude-plugin loomwright/skills loomwright/agents loomwright/commands loomwright/hooks 2>&1
    echo "(empty output above == no probe write leaked into a tracked plugin surface)"

    banner "SCRATCH REMOVAL"
    echo "scratch: $SCRATCH"
    if [ "$restore_ok" = "0" ]; then
      echo "PRESERVED — a restore assertion failed and the backup must survive for the operator."
    else
      rm -rf "$SCRATCH" && echo "removed" || echo "removal FAILED"
    fi
    echo
    echo "teardown complete: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } 2>&1 | tee "$LOG_T"
}
trap teardown EXIT INT TERM

# ---------------------------------------------------------------------------------------
# Phase 0 (preflight + fixtures + install) and Unknown A — logged to the Unknown A transcript
# ---------------------------------------------------------------------------------------

phase0_and_a() {
  banner "PHASE 0 — PREFLIGHT  ($(date -u +%Y-%m-%dT%H:%M:%SZ))"
  echo "repo root      : $REPO_ROOT"
  echo "scratch        : $SCRATCH"
  echo "probe deadline : ${DEADLINE}s per nested \`claude -p\`"
  echo "cli deadline   : ${CLI_DEADLINE}s per \`claude plugin ...\` subcommand"
  echo "nonce          : $NONCE"
  echo
  step pf-version "$CLI_DEADLINE" claude --version
  step pf-plugin-list "$CLI_DEADLINE" claude plugin list
  cp "$SCRATCH/pf-plugin-list.out" "$SCRATCH/baseline-plugin-list.txt" 2>/dev/null
  step pf-market-list "$CLI_DEADLINE" claude plugin marketplace list
  cp "$SCRATCH/pf-market-list.out" "$SCRATCH/baseline-marketplace-list.txt" 2>/dev/null

  banner "PHASE 0 — RESOLVE THE INSTALLED loomwright BODY (for Unknown A arm 2)"
  echo "Authority is the plugin manager's own installed_plugins.json record, cross-checked"
  echo "against \`claude plugin details\`. This is NOT an \`ls ~/.claude/plugins/cache/\`"
  echo "guess — that directory holds stale leftovers and is a recorded trap in this project."
  echo
  step pf-details "$CLI_DEADLINE" claude plugin details loomwright
  LOOMWRIGHT_INSTALL_PATH="$(python3 - <<'PY' 2>/dev/null
import json, os
p = os.path.expanduser("~/.claude/plugins/installed_plugins.json")
try:
    d = json.load(open(p))
except Exception:
    print(""); raise SystemExit
for key, entries in d.get("plugins", {}).items():
    if key.split("@")[0] == "loomwright":
        for e in entries:
            print(e.get("installPath", "")); raise SystemExit
print("")
PY
)"
  echo "LOOMWRIGHT_INSTALL_PATH=[$LOOMWRIGHT_INSTALL_PATH]"
  INSTALLED_SKILL="$LOOMWRIGHT_INSTALL_PATH/skills/quality-checklist/SKILL.md"
  echo "INSTALLED_SKILL=[$INSTALLED_SKILL]"
  echo "\$ ls -la \$INSTALLED_SKILL"
  ls -la "$INSTALLED_SKILL" 2>&1
  echo
  echo "marker asserted by arm 2: [$MARKER]"
  echo "\$ grep -cF \"\$MARKER\" \$INSTALLED_SKILL     # presence IN THE INSTALLED BODY, not the repo copy"
  count_matches "$INSTALLED_SKILL" "$MARKER"
  echo "\$ grep -rlF \"\$MARKER\" \$LOOMWRIGHT_INSTALL_PATH   # distinctiveness: which installed files carry it"
  grep -rlF -- "$MARKER" "$LOOMWRIGHT_INSTALL_PATH" 2>/dev/null
  echo "(exactly one file above == the phrase is unique in the installed body, so a hit in"
  echo " the agent's output cannot have come from some other preloaded skill)"

  banner "PHASE 0 — GENERATE THE THROWAWAY FIXTURES"
  mkdir -p "$MARKET_DIR/.claude-plugin" "$OUT_DIR"
  mkdir -p "$MARKET_DIR/$HOST_PLUGIN/.claude-plugin" "$MARKET_DIR/$HOST_PLUGIN/skills/probe-host-skill"
  mkdir -p "$MARKET_DIR/$CONSUMER_PLUGIN/.claude-plugin" "$MARKET_DIR/$CONSUMER_PLUGIN/agents" "$MARKET_DIR/$CONSUMER_PLUGIN/hooks"

  cat > "$MARKET_DIR/.claude-plugin/marketplace.json" <<JSON
{
  "name": "$MARKET_NAME",
  "owner": { "name": "cross-plugin resolution probe (throwaway)" },
  "plugins": [
    { "name": "$HOST_PLUGIN", "source": "./$HOST_PLUGIN", "description": "Throwaway probe plugin that OWNS the sentinel skill.", "version": "0.0.1" },
    { "name": "$CONSUMER_PLUGIN", "source": "./$CONSUMER_PLUGIN", "description": "Throwaway probe plugin whose agents preload skills owned by OTHER plugins.", "version": "0.0.1" }
  ]
}
JSON

  cat > "$MARKET_DIR/$HOST_PLUGIN/.claude-plugin/plugin.json" <<JSON
{
  "name": "$HOST_PLUGIN",
  "version": "0.0.1",
  "description": "Throwaway cross-plugin resolution probe — owns the sentinel skill.",
  "author": { "name": "cross-plugin resolution probe" },
  "license": "MIT"
}
JSON

  cat > "$MARKET_DIR/$HOST_PLUGIN/skills/probe-host-skill/SKILL.md" <<SKILL
---
name: probe-host-skill
description: Throwaway cross-plugin preload probe skill owned by probe-host. Carries a run-scoped sentinel.
version: "0.0.1"
---

# Probe host skill

The cross-plugin preload sentinel for this run is:

$NONCE

If you can see the sentinel above, this skill body was preloaded into your context.
SKILL

  cat > "$MARKET_DIR/$CONSUMER_PLUGIN/.claude-plugin/plugin.json" <<JSON
{
  "name": "$CONSUMER_PLUGIN",
  "version": "0.0.1",
  "description": "Throwaway cross-plugin resolution probe — agents preload OTHER plugins' skills; hooks print CLAUDE_PLUGIN_ROOT.",
  "author": { "name": "cross-plugin resolution probe" },
  "license": "MIT"
}
JSON

  # Tool isolation, following this repo's own `tools:` + `disallowedTools:` idiom
  # (loomwright/agents/plan-reviewer.md declares the full list, then subtracts down).
  # Here the subtraction removes every filesystem-read capability — no Read/Glob/Grep, and
  # no Bash/Task/WebFetch/TaskOutput either — leaving ONLY `WebSearch`, which reaches the
  # network and never the local filesystem. Preload is therefore the only channel by which
  # the sentinel can reach this agent's output.
  #
  # Why not subtract WebSearch too? Because a total subtraction is REFUSED at spawn — see
  # probe-zero-tools-agent below, which preserves that refusal as a control arm.
  cat > "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-agent.md" <<'AGENT'
---
name: probe-consumer:probe-agent
description: Throwaway probe agent. Preloads a skill owned by a DIFFERENT plugin (probe-host) and echoes its sentinel.
tools: Read, Write, Edit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebSearch, WebFetch
disallowedTools: Read, Write, Edit, NotebookEdit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebFetch
model: inherit
maxTurns: 3
skills:
  - probe-host-skill
---

# Probe agent (cross-plugin preload sentinel)

You have NO tools. Answer from your context only.

Your preloaded skills — if cross-plugin preload resolves — contain a token beginning
`XPLUGIN-NONCE-`. Output that full token on one line prefixed with `SENTINEL: `.

If no such token is present in your context, output exactly:

    SENTINEL: ABSENT

Never invent, guess, reconstruct, or partially complete a token. Output the one line and
nothing else.
AGENT

  cat > "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-checklist-agent.md" <<'AGENT'
---
name: probe-consumer:probe-checklist-agent
description: Throwaway probe agent. Preloads the REAL loomwright-owned `quality-checklist` skill (read-only corroboration arm).
tools: Read, Write, Edit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebSearch, WebFetch
disallowedTools: Read, Write, Edit, NotebookEdit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebFetch
model: inherit
maxTurns: 3
skills:
  - quality-checklist
---

# Probe agent (read-only corroboration arm)

You have NO tools. Answer from your context only.

If a skill named `quality-checklist` is present in your context, reproduce its
"Before Starting Any Task" checklist items VERBATIM, one per line, each prefixed with
`ITEM: `. Copy the text exactly as it appears — do not paraphrase, normalise or improve it.

If no skill named `quality-checklist` is present in your context, output exactly:

    CHECKLIST: ABSENT

Never reconstruct the checklist from memory or from general knowledge of what quality
checklists usually contain. If it is not in your context, say ABSENT.
AGENT

  # CONTROL ARM. Identical to probe-agent except that the subtraction is TOTAL. This
  # documents a spawn-time gate discovered by the first run of this probe: an agent whose
  # resolved tool list is empty is REFUSED before it ever runs. Kept as a fixture because
  # it is a real constraint on any companion plugin that tries to harden an agent by
  # subtracting tools — the refusal is silent in neither direction, it simply fails the
  # spawn, and a brief that assumed "no tools" was a valid hardening would be wrong.
  cat > "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-zero-tools-agent.md" <<'AGENT'
---
name: probe-consumer:probe-zero-tools-agent
description: Throwaway CONTROL agent. Subtracts every tool, to record what happens at spawn time.
tools: Read, Write, Edit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebSearch, WebFetch
disallowedTools: Read, Write, Edit, NotebookEdit, Glob, Grep, Bash, Task, TaskOutput, LSP, WebSearch, WebFetch
model: inherit
maxTurns: 3
skills:
  - probe-host-skill
---

# Control agent (total tool subtraction)

Output `SENTINEL: ` followed by the `XPLUGIN-NONCE-` token from your preloaded skills, or
`SENTINEL: ABSENT` if there is none.
AGENT

  # Unknown B. The hook writes to an ABSOLUTE scratch path (baked in below), because a
  # relative path would land in whatever cwd the triggering session happened to have.
  #
  #   RAW=           the literal ${CLAUDE_PLUGIN_ROOT} expansion, bracketed so that an
  #                  empty value is VISIBLE rather than invisible
  #   BRACE_DEFAULT= the same name with a shell default. If Claude Code substitutes the
  #                  token textually rather than exporting an env var, this longer form
  #                  will NOT match its substitution pattern, and what we see is the
  #                  shell's own expansion — which distinguishes the two mechanisms
  #   ENV_PRESENT=   whether CLAUDE_PLUGIN_ROOT exists in the hook process's environment
  #                  at all — this is what separates "unset" from "set but empty"
  #
  # `|| true` is present ON PURPOSE: it is this plugin family's convention, and it is
  # exactly why a green run proves nothing. The FILE CONTENT is the evidence, never the
  # exit status.
  cat > "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json" <<'JSON'
{
  "description": "Throwaway cross-plugin resolution probe — records the expanded CLAUDE_PLUGIN_ROOT of a SECOND plugin.",
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "{ printf 'RAW=[%s]\\n' \"${CLAUDE_PLUGIN_ROOT}\"; printf 'BRACE_DEFAULT=[%s]\\n' \"${CLAUDE_PLUGIN_ROOT:-__UNSET_OR_EMPTY__}\"; printf 'ENV_PRESENT=[%s]\\n' \"$(env | grep -c '^CLAUDE_PLUGIN_ROOT=')\"; printf 'HOOK_CWD=[%s]\\n' \"$PWD\"; printf 'HOOK_FIRED_AT=[%s]\\n' \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"; } >> '@@OUT@@/unknown-b-plugin-root.txt' 2>&1 || true"
          }
        ]
      }
    ]
  }
}
JSON
  # Bake the absolute output path in by substitution rather than with an unquoted heredoc,
  # so that ${CLAUDE_PLUGIN_ROOT} above survives VERBATIM into the generated JSON instead
  # of being expanded by this script's own shell.
  sed -i.bak "s|@@OUT@@|$OUT_DIR|g" "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json"
  rm -f "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json.bak"

  echo "\$ find \$MARKET_DIR -type f"
  find "$MARKET_DIR" -type f | sed "s|$SCRATCH/||" | sort
  echo
  echo "\$ cat probe-consumer/agents/probe-agent.md      # the tool-isolation frontmatter"
  cat "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-agent.md"
  echo
  echo "\$ cat probe-consumer/agents/probe-checklist-agent.md"
  cat "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-checklist-agent.md"
  echo
  echo "\$ cat probe-consumer/agents/probe-zero-tools-agent.md   # the control arm"
  cat "$MARKET_DIR/$CONSUMER_PLUGIN/agents/probe-zero-tools-agent.md"
  echo
  echo "\$ cat probe-consumer/hooks/hooks.json          # the Unknown B hook, absolute path baked in"
  cat "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json"
  echo
  echo "\$ python3 -c 'json.load(...)'                  # the generated hooks.json is valid JSON"
  python3 -c "import json,sys; json.load(open(sys.argv[1])); print('hooks.json: valid JSON')" \
    "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json" 2>&1

  banner "PHASE 0 — VALIDATE + INSTALL (--scope local ONLY)"
  step pf-validate-host "$CLI_DEADLINE" claude plugin validate "$MARKET_DIR/$HOST_PLUGIN"
  step pf-validate-consumer "$CLI_DEADLINE" claude plugin validate "$MARKET_DIR/$CONSUMER_PLUGIN"
  echo "state of $LOCAL_SETTINGS before install: $SETTINGS_EXISTED"
  echo
  cd "$REPO_ROOT" || return 1
  step in-market-add "$CLI_DEADLINE" claude plugin marketplace add "$MARKET_DIR" --scope local
  step in-install-host "$CLI_DEADLINE" claude plugin install "$HOST_PLUGIN@$MARKET_NAME" --scope local
  step in-install-consumer "$CLI_DEADLINE" claude plugin install "$CONSUMER_PLUGIN@$MARKET_NAME" --scope local
  step in-plugin-list "$CLI_DEADLINE" claude plugin list
  step in-details-consumer "$CLI_DEADLINE" claude plugin details "$CONSUMER_PLUGIN"

  # ---------------------------------------------------------------------------------
  banner "UNKNOWN A — ARM 1 (PRIMARY): run-scoped nonce in a generated fixture"
  # ---------------------------------------------------------------------------------
  echo "mutation-target == preload-source? YES, BY CONSTRUCTION. This script authored"
  echo "  $MARKET_DIR/$HOST_PLUGIN/skills/probe-host-skill/SKILL.md"
  echo "and that same file is what the marketplace install copied. No tracked file is"
  echo "involved anywhere, so the 'nonce written to a snapshot the session never loads'"
  echo "failure — which can only ever produce a FALSE 'DOES NOT RESOLVE' — is impossible here."
  echo
  echo "\$ grep -cF \"\$NONCE\" probe-host/skills/probe-host-skill/SKILL.md"
  count_matches "$MARKET_DIR/$HOST_PLUGIN/skills/probe-host-skill/SKILL.md" "$NONCE"

  cat > "$SCRATCH/prompt-a1.txt" <<PROMPT
Run id $NONCE-PARENT-A1.
Use the Task tool exactly once, with subagent_type "probe-consumer:probe-consumer:probe-agent",
and give it this prompt: "Output your sentinel line as instructed."
Then output ONLY these two lines and nothing else:
SPAWN: ok
RELAY: <the subagent's final message, verbatim>
If the Task call errors, instead output ONLY:
SPAWN: error
RELAY: <the verbatim error text>
Do not add commentary. Do not invent or complete any token yourself.
PROMPT

  echo
  echo "\$ claude -p --tools \"$PARENT_TOOLS\" < prompt-a1.txt   (bounded ${DEADLINE}s)"
  echo "  The parent session's tool set is restricted to [$PARENT_TOOLS] — no Read, Glob,"
  echo "  Grep or Bash — so the parent cannot read the sentinel off disk and relay it."
  echo "  Isolation therefore holds at BOTH levels: the subagent has no filesystem-read"
  echo "  tool, and neither does the process observing it."
  echo "--- prompt (verbatim) ---"; cat "$SCRATCH/prompt-a1.txt"; echo "--- end prompt ---"
  claude_bounded a1 "$SCRATCH/prompt-a1.txt" --tools "$PARENT_TOOLS"
  emit_capture a1 "$?"
  echo
  echo "\$ grep -cF \"\$NONCE\" <arm 1 captured output>    # <== THE assertion for Unknown A arm 1"
  count_matches "$SCRATCH/a1.out" "$NONCE"
  echo "(>=1 == the nonce reached the agent's output through preload; 0 == it did not)"

  # ---------------------------------------------------------------------------------
  banner "UNKNOWN A — ARM 2 (CORROBORATION, STRICTLY READ-ONLY): the real loomwright skill"
  # ---------------------------------------------------------------------------------
  echo "installed loomwright body (resolved in Phase 0): $LOOMWRIGHT_INSTALL_PATH"
  echo "marker asserted:                                 [$MARKER]"
  echo "This arm writes nothing. It only spawns an agent whose skills: names quality-checklist."
  echo
  echo "EVIDENTIAL WEIGHT: this arm CORROBORATES arm 1 and NEVER OVERRIDES it. Unlike the"
  echo "run-scoped nonce, a pre-existing phrase cannot fully exclude reproduction from the"
  echo "model's prior knowledge, so a hit here is strictly weaker evidence than a hit in"
  echo "arm 1. If the two arms disagree, that disagreement is the finding — arm 1 rules."

  cat > "$SCRATCH/prompt-a2.txt" <<PROMPT
Run id $NONCE-PARENT-A2.
Use the Task tool exactly once, with subagent_type "probe-consumer:probe-consumer:probe-checklist-agent",
and give it this prompt: "Reproduce your checklist as instructed."
Then output ONLY these two lines and nothing else:
SPAWN: ok
RELAY: <the subagent's final message, verbatim>
If the Task call errors, instead output ONLY:
SPAWN: error
RELAY: <the verbatim error text>
Do not add commentary. Do not write the checklist yourself.
PROMPT

  echo
  echo "\$ claude -p --tools \"$PARENT_TOOLS\" < prompt-a2.txt   (bounded ${DEADLINE}s)"
  echo "--- prompt (verbatim) ---"; cat "$SCRATCH/prompt-a2.txt"; echo "--- end prompt ---"
  claude_bounded a2 "$SCRATCH/prompt-a2.txt" --tools "$PARENT_TOOLS"
  emit_capture a2 "$?"
  echo
  echo "\$ grep -cF \"\$MARKER\" <arm 2 captured output>   # <== THE assertion for Unknown A arm 2"
  count_matches "$SCRATCH/a2.out" "$MARKER"

  # ---------------------------------------------------------------------------------
  banner "UNKNOWN A — CONTROL ARM: what a TOTAL tool subtraction does at spawn time"
  # ---------------------------------------------------------------------------------
  echo "probe-zero-tools-agent is identical to probe-agent except that disallowedTools"
  echo "subtracts EVERY tool, including the WebSearch that probe-agent keeps. This arm"
  echo "exists because the first run"
  echo "of this probe accidentally shipped that configuration and learned something the"
  echo "brief did not anticipate. It is kept as a designed control rather than discarded."
  echo
  echo "It also protects the two arms above from a specific misreading: if arm 1 had"
  echo "returned no sentinel, one might conclude 'cross-plugin preload does not resolve'."
  echo "This arm shows the OTHER thing that produces no sentinel — a refused spawn — so the"
  echo "two are distinguishable in the record instead of being conflated."

  cat > "$SCRATCH/prompt-a0.txt" <<PROMPT
Run id $NONCE-PARENT-A0.
Use the Task tool exactly once with subagent_type "probe-consumer:probe-consumer:probe-zero-tools-agent"
and the prompt "Output your sentinel line as instructed."
Then output ONLY these two lines and nothing else:
OUTCOME: <resolved|error>
DETAIL: <the subagent's final message verbatim if it resolved, otherwise the VERBATIM error text>
Do not paraphrase the error. Do not retry with a different subagent_type.
PROMPT
  echo
  echo "\$ claude -p --tools \"$PARENT_TOOLS\" < prompt-a0.txt   (bounded ${DEADLINE}s)"
  echo "--- prompt (verbatim) ---"; cat "$SCRATCH/prompt-a0.txt"; echo "--- end prompt ---"
  claude_bounded a0 "$SCRATCH/prompt-a0.txt" --tools "$PARENT_TOOLS"
  emit_capture a0 "$?"
}

# ---------------------------------------------------------------------------------------
# Unknown B
# ---------------------------------------------------------------------------------------

phase_b() {
  banner "UNKNOWN B — \${CLAUDE_PLUGIN_ROOT} INSIDE A SECOND PLUGIN'S hooks.json"
  BFILE="$OUT_DIR/unknown-b-plugin-root.txt"
  echo "hook source     : $MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json   (SessionStart)"
  echo "hook output file: $BFILE"
  echo
  echo "\$ cat probe-consumer/hooks/hooks.json"
  cat "$MARKET_DIR/$CONSUMER_PLUGIN/hooks/hooks.json" 2>&1
  echo
  echo "pre-trigger state:"
  echo "\$ ls -la \$BFILE"; ls -la "$BFILE" 2>&1
  echo
  echo "trigger: a fresh \`claude -p\` session — SessionStart fires on session creation."
  echo "\$ claude -p --tools \"\" < prompt-b.txt            (bounded ${DEADLINE}s)"
  printf '%s' "Run id $NONCE-PARENT-B. Reply with exactly: TRIGGERED" > "$SCRATCH/prompt-b.txt"
  claude_bounded b "$SCRATCH/prompt-b.txt" --tools ""
  emit_capture b "$?"
  echo
  echo "post-trigger state:"
  echo "\$ ls -la \$BFILE"; ls -la "$BFILE" 2>&1
  echo
  echo "\$ cat \$BFILE      # <== THE evidence for Unknown B. Exit status proves NOTHING here:"
  echo "                     #     the '|| true' convention makes an unset expansion exit 0."
  if [ -f "$BFILE" ]; then
    cat "$BFILE" 2>&1
    echo "--- end file ---"
    echo
    echo "HOW TO READ THE DISCRIMINATOR:"
    echo "  RAW=[<path>]                   -> it expanded; the path IS the answer (per-plugin or not)"
    echo "  RAW=[]  with ENV_PRESENT=[1]   -> the variable EXISTS but is EMPTY  (silent no-op under '|| true')"
    echo "  RAW=[]  with ENV_PRESENT=[0]   -> the variable is UNSET             (silent no-op under '|| true')"
    echo "  RAW=[\${CLAUDE_PLUGIN_ROOT}]    -> no substitution at all; the literal token reached the shell"
  else
    echo "FILE ABSENT."
    echo "This is a RECORDED RESULT, not an inconclusive skip: either the second plugin's"
    echo "hooks.json was never registered (so the hook did not fire at all), or it fired and"
    echo "wrote nothing. Either way the QA telemetry / token-ledger fan-out that Unknown B"
    echo "exists to protect would be silently lost."
    echo "\$ ls -la \$OUT_DIR"; ls -la "$OUT_DIR" 2>&1
  fi
}

# ---------------------------------------------------------------------------------------
# Unknown C
# ---------------------------------------------------------------------------------------

phase_c() {
  banner "UNKNOWN C — CROSS-PLUGIN Task(subagent_type:) FROM A LOOMWRIGHT SURFACE"
  echo "Both forms are attempted AGAINST THE PROBE PLUGIN. The loomwright precedent"
  echo "(loomwright:loomwright:<role> resolves, single-prefix errors — measured 2026-08-08)"
  echo "is advisory context ONLY and is never substituted for this measurement."
  echo
  echo "probe agent frontmatter name : probe-consumer:probe-agent"
  echo "  single-prefix form attempted : probe-consumer:probe-agent"
  echo "  doubled-prefix form attempted: probe-consumer:probe-consumer:probe-agent"
  echo
  echo "The observing session runs with cwd=$REPO_ROOT and the loomwright plugin enabled,"
  echo "so the spawn originates from a loomwright surface, as the unknown requires."

  local form label
  for form in "probe-consumer:probe-agent" "probe-consumer:probe-consumer:probe-agent"; do
    label="c-$(echo "$form" | tr ':' '_')"
    echo
    echo "-------- attempting subagent_type: \"$form\" --------"
    cat > "$SCRATCH/prompt-$label.txt" <<PROMPT
Run id $NONCE-PARENT-C.
Use the Task tool exactly once with subagent_type "$form" and the prompt
"Output your sentinel line as instructed."
Then output ONLY these three lines and nothing else:
SUBAGENT_TYPE: $form
OUTCOME: <resolved|error>
DETAIL: <the subagent's final message verbatim if it resolved, otherwise the VERBATIM error text you received>
Do not paraphrase the error. Do not retry with a different subagent_type.
PROMPT
    echo "--- prompt (verbatim) ---"; cat "$SCRATCH/prompt-$label.txt"; echo "--- end prompt ---"
    claude_bounded "$label" "$SCRATCH/prompt-$label.txt" --tools "$PARENT_TOOLS"
    emit_capture "$label" "$?"
    echo "\$ grep -cF \"\$NONCE\" <captured output>   # did the sentinel come back through this form?"
    count_matches "$SCRATCH/$label.out" "$NONCE"
  done
}

# ---------------------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------------------

mkdir -p "$SCRATCH" "$OUT_DIR"

# Every nested `claude` call must run with cwd == the repo root: `--scope local` writes to
# (and is read back from) the local settings of the CURRENT project directory, so a probe
# observed from anywhere else would simply not see the plugins this run installed.
cd "$REPO_ROOT" || { echo "cannot cd to repo root $REPO_ROOT" >&2; exit 1; }

# Capture and back up the local settings file BEFORE anything touches plugin state.
if [ -f "$LOCAL_SETTINGS" ]; then
  SETTINGS_EXISTED="present"
  cp "$LOCAL_SETTINGS" "$SETTINGS_BACKUP"
else
  SETTINGS_EXISTED="absent"
fi

phase0_and_a 2>&1 | tee "$LOG_A"
phase_b      2>&1 | tee "$LOG_B"
phase_c      2>&1 | tee "$LOG_C"

# Teardown runs from the EXIT trap.
exit 0
