#!/usr/bin/env bash
# gen-color-legend.sh — generate the "Color Legend (Status Line)" table in
# loomwright/docs/ARCHITECTURE_CONTRACTS.md from agent frontmatter, and check it for drift.
#
# WHY: the legend was hand-maintained and drifted — on 2026-09-01 it carried 12 rows while 14
# agents declared a `color:`. Nothing mechanical noticed, because check-doc-currency.sh has no
# legend check. This script makes the table GENERATED OUTPUT with a `--check` mode wired into
# that gate, so the same drift cannot recur by hand.
#
# THE ONLY LOOKUP IS A PUBLISHED STANDARD.
#   Agent column = frontmatter `name:` minus the `loomwright:` prefix. Authoritative and exact —
#                  deliberately NOT a display-name map, which would have to be hand-edited on
#                  every agent added (the exact drift class this replaces).
#   Hex column   = frontmatter `color:` verbatim.
#   Color column = the CSS named-colour table below, keyed by HEX, camelCase-split.
#
#   Honest limit, stated rather than papered over: that CSS table IS a map embedded here. The
#   claim is not "no map anywhere" — it is that the only map is a PUBLISHED STANDARD keyed by
#   hex, so it cannot drift RELATIVE TO FRONTMATTER: change an agent's `color:` and the name
#   follows automatically. The table is the full standard list (147 entries + `RebeccaPurple`),
#   NOT a subset keyed to today's agent set: a subset would silently return the no-name fallback
#   for every colour a future agent picks. test-gen-color-legend.sh pins both branches — a hex
#   that is not a CSS name renders the em-dash fallback, and a CSS name from OUTSIDE the 14 in
#   use (`#FA8072` -> Salmon) must still resolve.
#
# SENTINELS: the table is written between
#   <!-- loomwright:color-legend BEGIN (generated by gen-color-legend.sh) -->
#   <!-- loomwright:color-legend END -->
# so a re-stamp keys off the marker rather than off a heading, and is idempotent. `--write`
# REFUSES a document with no marker pair rather than guessing where the table goes.
#
# MODES
#   (no args)   emit the generated block to stdout. Writes nothing.
#   --write     replace the marked block in the doc, in place. Idempotent (byte-compare first).
#   --check     compare the doc's marked block against the generated one. Exit 1 + a specific
#               diagnostic (`LEGEND DRIFT` / `LEGEND MARKERS MISSING`) on any mismatch.
#
# Overrides (self-test fixtures only; unset in real runs):
#   --agents-dir <dir>   directory of agent *.md files
#   --doc <path>         the document carrying the marked block
#
# EXIT CODES: 0 = clean / emitted. 1 = drift, missing markers, or an error (unreadable agents
# dir, no agents found, unreadable doc). This is a CORRECTNESS GATE, not a runtime emitter —
# it fails CLOSED and carries no `|| true` (CLAUDE.md §"Failure-Mode Invariants").
#
# Portability: bash 3.2 / BSD userland safe. No associative arrays, no GNU-only sed/date/stat
# flags, no `${var//…}` pattern substitution. LC_ALL=C pins glob collation so row order is
# identical on macOS and on Linux CI.

set -uo pipefail
export LC_ALL=C

script_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"

AGENTS_DIR="$repo_root/loomwright/agents"
DOC="$repo_root/loomwright/docs/ARCHITECTURE_CONTRACTS.md"
MODE="emit"

BEGIN_MARK='<!-- loomwright:color-legend BEGIN (generated by gen-color-legend.sh) -->'
END_MARK='<!-- loomwright:color-legend END -->'

while [ $# -gt 0 ]; do
  case "$1" in
    --write)       MODE="write" ;;
    --check)       MODE="check" ;;
    --agents-dir)  shift; AGENTS_DIR="${1:-}" ;;
    --doc)         shift; DOC="${1:-}" ;;
    *) echo "gen-color-legend: unknown argument '$1' (expected --write | --check | --agents-dir <dir> | --doc <path>)" >&2; exit 1 ;;
  esac
  shift
done

[ -d "$AGENTS_DIR" ] || { echo "gen-color-legend: agents directory not found: $AGENTS_DIR" >&2; exit 1; }

# ---------------------------------------------------------------------------
# The CSS named-colour table (the published standard, keyed by hex).
# One `#RRGGBB Name` pair per line, uppercase hex. Where two names share a hex
# (Aqua/Cyan, Fuchsia/Magenta, Gray/Grey spellings) the CSS-canonical spelling
# is listed FIRST and wins, because the lookup takes the first match.
# ---------------------------------------------------------------------------
css_table() {
  cat <<'CSSEOF'
#F0F8FF AliceBlue
#FAEBD7 AntiqueWhite
#00FFFF Aqua
#7FFFD4 Aquamarine
#F0FFFF Azure
#F5F5DC Beige
#FFE4C4 Bisque
#000000 Black
#FFEBCD BlanchedAlmond
#0000FF Blue
#8A2BE2 BlueViolet
#A52A2A Brown
#DEB887 BurlyWood
#5F9EA0 CadetBlue
#7FFF00 Chartreuse
#D2691E Chocolate
#FF7F50 Coral
#6495ED CornflowerBlue
#FFF8DC Cornsilk
#DC143C Crimson
#00008B DarkBlue
#008B8B DarkCyan
#B8860B DarkGoldenrod
#A9A9A9 DarkGray
#006400 DarkGreen
#BDB76B DarkKhaki
#8B008B DarkMagenta
#556B2F DarkOliveGreen
#FF8C00 DarkOrange
#9932CC DarkOrchid
#8B0000 DarkRed
#E9967A DarkSalmon
#8FBC8F DarkSeaGreen
#483D8B DarkSlateBlue
#2F4F4F DarkSlateGray
#00CED1 DarkTurquoise
#9400D3 DarkViolet
#FF1493 DeepPink
#00BFFF DeepSkyBlue
#696969 DimGray
#1E90FF DodgerBlue
#B22222 FireBrick
#FFFAF0 FloralWhite
#228B22 ForestGreen
#FF00FF Fuchsia
#DCDCDC Gainsboro
#F8F8FF GhostWhite
#FFD700 Gold
#DAA520 Goldenrod
#808080 Gray
#008000 Green
#ADFF2F GreenYellow
#F0FFF0 Honeydew
#FF69B4 HotPink
#CD5C5C IndianRed
#4B0082 Indigo
#FFFFF0 Ivory
#F0E68C Khaki
#E6E6FA Lavender
#FFF0F5 LavenderBlush
#7CFC00 LawnGreen
#FFFACD LemonChiffon
#ADD8E6 LightBlue
#F08080 LightCoral
#E0FFFF LightCyan
#FAFAD2 LightGoldenrodYellow
#D3D3D3 LightGray
#90EE90 LightGreen
#FFB6C1 LightPink
#FFA07A LightSalmon
#20B2AA LightSeaGreen
#87CEFA LightSkyBlue
#778899 LightSlateGray
#B0C4DE LightSteelBlue
#FFFFE0 LightYellow
#00FF00 Lime
#32CD32 LimeGreen
#FAF0E6 Linen
#800000 Maroon
#66CDAA MediumAquamarine
#0000CD MediumBlue
#BA55D3 MediumOrchid
#9370DB MediumPurple
#3CB371 MediumSeaGreen
#7B68EE MediumSlateBlue
#00FA9A MediumSpringGreen
#48D1CC MediumTurquoise
#C71585 MediumVioletRed
#191970 MidnightBlue
#F5FFFA MintCream
#FFE4E1 MistyRose
#FFE4B5 Moccasin
#FFDEAD NavajoWhite
#000080 Navy
#FDF5E6 OldLace
#808000 Olive
#6B8E23 OliveDrab
#FFA500 Orange
#FF4500 OrangeRed
#DA70D6 Orchid
#EEE8AA PaleGoldenrod
#98FB98 PaleGreen
#AFEEEE PaleTurquoise
#DB7093 PaleVioletRed
#FFEFD5 PapayaWhip
#FFDAB9 PeachPuff
#CD853F Peru
#FFC0CB Pink
#DDA0DD Plum
#B0E0E6 PowderBlue
#800080 Purple
#663399 RebeccaPurple
#FF0000 Red
#BC8F8F RosyBrown
#4169E1 RoyalBlue
#8B4513 SaddleBrown
#FA8072 Salmon
#F4A460 SandyBrown
#2E8B57 SeaGreen
#FFF5EE SeaShell
#A0522D Sienna
#C0C0C0 Silver
#87CEEB SkyBlue
#6A5ACD SlateBlue
#708090 SlateGray
#FFFAFA Snow
#00FF7F SpringGreen
#4682B4 SteelBlue
#D2B48C Tan
#008080 Teal
#D8BFD8 Thistle
#FF6347 Tomato
#40E0D0 Turquoise
#EE82EE Violet
#F5DEB3 Wheat
#FFFFFF White
#F5F5F5 WhiteSmoke
#FFFF00 Yellow
#9ACD32 YellowGreen
CSSEOF
}

# css_name <#RRGGBB-uppercase> -> the camelCase-split CSS name, or the empty string.
css_name() {
  local hex="$1" line name
  line="$(css_table | grep -m1 -F -- "$hex " || true)"
  [ -n "$line" ] || return 0
  name="${line#* }"
  # camelCase -> spaced words: insert a space at every lower->UPPER boundary.
  printf '%s' "$name" | sed 's/\([a-z]\)\([A-Z]\)/\1 \2/g'
}

# ---------------------------------------------------------------------------
# Read agent frontmatter -> generated block on stdout.
# Only the FIRST frontmatter block of each file is read (awk `n==1`), so a
# `name:`/`color:` appearing in the prose body can never be mistaken for one.
# ---------------------------------------------------------------------------
frontmatter_field() {
  local file="$1" key="$2" val
  val="$(awk -v k="^$2:" '/^---$/{n++; next} n==1 && $0 ~ k {sub(/^[^:]*:[[:space:]]*/, ""); print; exit}' "$file")"
  # strip surrounding double quotes and trailing whitespace
  val="${val%\"}"; val="${val#\"}"
  printf '%s' "$val"
}

generate_block() {
  local f name color hex word rows=0
  printf '%s\n' "$BEGIN_MARK"
  printf '%s\n' '| Agent | Color | Hex |'
  printf '%s\n' '|-------|-------|-----|'
  for f in "$AGENTS_DIR"/*.md; do
    [ -f "$f" ] || continue
    name="$(frontmatter_field "$f" name)"
    color="$(frontmatter_field "$f" color)"
    [ -n "$name" ] || continue
    [ -n "$color" ] || continue
    name="${name#loomwright:}"
    hex="$(printf '%s' "$color" | tr '[:lower:]' '[:upper:]')"
    word="$(css_name "$hex")"
    [ -n "$word" ] || word='—'
    printf '| %s | %s | `%s` |\n' "$name" "$word" "$color"
    rows=$((rows + 1))
  done
  printf '%s\n' "$END_MARK"
  [ "$rows" -gt 0 ] || return 1
  return 0
}

# extract_block <doc> -> the marked block (inclusive of both markers) on stdout.
# Returns 1 when the marker pair is not present exactly once in the right order.
extract_block() {
  local doc="$1" b e
  [ -f "$doc" ] || return 1
  b="$(grep -c -F -- "$BEGIN_MARK" "$doc" || true)"
  e="$(grep -c -F -- "$END_MARK" "$doc" || true)"
  case "$b$e" in *[!0-9]*) return 1 ;; esac
  [ "$b" = "1" ] && [ "$e" = "1" ] || return 1
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    index($0, b) { on=1 }
    on { print }
    index($0, e) { if (on) exit }
  ' "$doc"
}

GENERATED="$(generate_block)" || {
  echo "gen-color-legend: no agent frontmatter with both name: and color: found under $AGENTS_DIR — refusing to emit an empty legend" >&2
  exit 1
}

case "$MODE" in
  emit)
    printf '%s\n' "$GENERATED"
    exit 0
    ;;

  check)
    if [ ! -f "$DOC" ]; then
      echo "gen-color-legend: LEGEND MARKERS MISSING — document not found: $DOC" >&2
      exit 1
    fi
    current="$(extract_block "$DOC")" || {
      echo "gen-color-legend: LEGEND MARKERS MISSING — $DOC does not carry exactly one '$BEGIN_MARK' / '$END_MARK' pair. Add the marker pair around the Color Legend (Status Line) table, then run: bash loomwright/scripts/gen-color-legend.sh --write" >&2
      exit 1
    }
    if [ "$current" = "$GENERATED" ]; then
      echo "✓ color-legend: the generated legend matches agent frontmatter ($(printf '%s\n' "$GENERATED" | grep -c '^| .* | .* | `#') rows)."
      exit 0
    fi
    echo "gen-color-legend: LEGEND DRIFT — the Color Legend (Status Line) block in $DOC does not match agent frontmatter." >&2
    echo "  Regenerate with: bash loomwright/scripts/gen-color-legend.sh --write" >&2
    echo "  --- in $DOC" >&2
    echo "  +++ generated from $AGENTS_DIR" >&2
    diff <(printf '%s\n' "$current") <(printf '%s\n' "$GENERATED") 2>/dev/null | sed 's/^/  /' >&2
    exit 1
    ;;

  write)
    if [ ! -f "$DOC" ]; then
      echo "gen-color-legend: document not found: $DOC" >&2
      exit 1
    fi
    if ! extract_block "$DOC" >/dev/null; then
      echo "gen-color-legend: LEGEND MARKERS MISSING — $DOC does not carry exactly one '$BEGIN_MARK' / '$END_MARK' pair. Refusing to guess where the table goes; add the marker pair by hand first." >&2
      exit 1
    fi
    current="$(extract_block "$DOC")"
    if [ "$current" = "$GENERATED" ]; then
      echo "color-legend: no-op — $DOC already matches agent frontmatter."
      exit 0
    fi
    tmp="$DOC.gen-color-legend.tmp.$$"
    gen_file="$DOC.gen-color-legend.block.$$"
    printf '%s\n' "$GENERATED" > "$gen_file" || { echo "gen-color-legend: could not stage the generated block" >&2; exit 1; }
    awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v gf="$gen_file" '
      index($0, b) && !done { inblock=1; while ((getline line < gf) > 0) print line; close(gf); done=1; next }
      inblock { if (index($0, e)) { inblock=0 }; next }
      { print }
    ' "$DOC" > "$tmp" || { rm -f "$tmp" "$gen_file"; echo "gen-color-legend: rewrite failed; $DOC is unchanged" >&2; exit 1; }
    rm -f "$gen_file"
    mv "$tmp" "$DOC" || { rm -f "$tmp"; echo "gen-color-legend: could not replace $DOC" >&2; exit 1; }
    echo "color-legend: wrote $(printf '%s\n' "$GENERATED" | grep -c '^| .* | .* | `#') rows into $DOC."
    exit 0
    ;;
esac
