#!/usr/bin/env bash
# pr-postmortem-gather.sh — READ-ONLY PR data gatherer for /pr-postmortem (Subtask 1).
#
# Input: ONE PR reference, either
#   https://github.com/OWNER/REPO/pull/N    (full URL)
#   OWNER/REPO#N                            (short form)
#
# Output: exactly ONE normalized JSON object on stdout, jq-built (injection-safe).
# On success the object carries NO `status` field:
#   {
#     "repo": "owner/repo", "number": 42, "title": "...",
#     "agent_generated_guess": true,
#     "additions": 120, "deletions": 30, "changed_files": 5,
#     "commits": [{"headline": "...", "is_review_fix": false}],
#     "review_rounds": 3,
#     "review_rounds_source": "fix_commits",
#     "review_comments": [{"author": "...", "snippet": "..."}],
#     "ci_checks": [{"name": "...", "state": "SUCCESS"}]
#   }
#
# On ANY failure (gh/jq missing or unauthenticated, PR private/not-found/inaccessible,
# unparseable input) it emits a jq-built unavailable object and exits 0:
#   {"status":"unavailable","reason":"<short reason>"}
# The presence of `status` is how the caller distinguishes the two shapes.
#
# INVARIANTS (acceptance criteria):
#   1. ALWAYS exits 0. No `set -e` mid-emit crash; the script absorbs every failure.
#   2. The success JSON is built with a SINGLE jq invocation using --arg/--argjson
#      ONLY — no untrusted PR text is ever string-interpolated into JSON.
#   3. Pure read: no writes to the analyzed repo, no network beyond `gh`, no
#      mutating sub-process.
#
# TESTABILITY: every `gh` call goes through "$GH_BIN" (default `gh`). The self-test
# stubs `gh` by putting a fake earlier on PATH (so GH_BIN resolves to the stub); it
# does NOT need to override GH_BIN explicitly. GH_BIN exists as an extra override hook.
#
# HEURISTICS (documented per acceptance criteria):
#   agent_generated_guess — true if the PR body matches (case-insensitively) any of
#     "Generated by Supervisor", "Generated with Claude Code", "Co-Authored-By: Claude",
#     or contains the 🤖 robot emoji; OR if any commit subject mentions "self-heal" or
#     STARTS with an agent task-id prefix ("bd-12a: …") or the Supervisor's worktree
#     commit convention ("subtask: …"). The task-id pattern is deliberately anchored to
#     the subject-leading "id:" form — a bare word-dash-number match would false-positive
#     on ordinary tokens (utf-8, sha-256, base-64) and pollute the seed corpus this
#     trend data exists to build. ("Co-Authored-By" is a body trailer, so it is matched
#     against the PR body, never against commit subjects where it cannot appear.)
#     Best-effort signal, not authoritative.
#   commits[].is_review_fix — true if the commit subject matches (case-insensitively)
#     any of: "address review", "review feedback", "fix review", "self-heal",
#     "addresses review", "review comment". A heuristic flag for review-churn commits.
#   review_rounds — derived as MAX of THREE signals: (a) count of is_review_fix
#     commits; (b) count of distinct CHURN-review submission timestamps — a review
#     counts as churn only when its state is CHANGES_REQUESTED, or COMMENTED with a
#     non-empty body (approval-only reviews / bare LGTM are NOT rounds); (c) count of
#     bot-authored ISSUE-COMMENT review rounds (see below). Using the max avoids
#     undercounting when one signal is absent; caveats: several fix commits inside a
#     single round can still overcount, as can two reviewers requesting changes within
#     one logical round (distinct submittedAt) — accepted noise for a trend signal.
#   bot issue-comment review rounds — some repos deliver review feedback as ISSUE
#     COMMENTS posted by a CI workflow (e.g. a claude-review job commenting as
#     `claude[bot]`), not as formal review objects — which left review_rounds at 0
#     despite real churn (the PR #47 miss). A comment is REVIEW-SHAPED when its
#     author login ends with "[bot]" AND its body carries a review marker (a markdown
#     heading containing "review", or the phrase "code review", case-insensitive). A
#     review-shaped bot comment counts as a ROUND only when at least one commit landed
#     AFTER it (comment created_at vs commit committedDate; ISO-8601 Z timestamps
#     compare lexicographically). Review-shaped bot comments are also appended to
#     review_comments[] as categorization evidence. Caveats: rebases/force-pushes can
#     reorder committedDate, and a final bot comment with no follow-up push is
#     (correctly) not a round — accepted noise.
#   review_rounds_source — names the dominant signal behind review_rounds:
#     "fix_commits" | "formal_reviews" | "bot_comments" | "none" (ties resolve in that
#     order, matching the pre-existing two-signal MAX precedence).
#
# FAIL-SAFE DEGRADE: the issue-comments fetch is a SECOND, optional gh call. On ANY
# failure (gh error, empty output, non-array JSON) it degrades to an empty list and
# the gatherer behaves exactly as it did before this signal existed — never a
# non-zero exit, never an unavailable emit for a comment-fetch-only failure.

set -uo pipefail
# Intentionally NO `set -e`: the fail-safe JSON emit must never be aborted mid-stream.

GH_BIN="${GH_BIN:-gh}"

# ---- emit_unavailable <reason> ---------------------------------------------
# Emit the jq-built unavailable object and exit 0. Falls back to a hand-built
# minimal object only if jq itself is missing (reason is a fixed/whitelisted slug
# in that path, so no injection hazard). Always exits 0.
emit_unavailable() {
  local reason="$1"
  if command -v jq >/dev/null 2>&1; then
    jq -cn --arg reason "$reason" '{status:"unavailable", reason:$reason}'
  else
    # jq absent: reason here is always a fixed internal slug (no quotes/backslashes),
    # so direct interpolation is JSON-safe.
    printf '{"status":"unavailable","reason":"%s"}\n' "$reason"
  fi
  exit 0
}

# ---- tool availability ------------------------------------------------------
command -v jq >/dev/null 2>&1 || emit_unavailable "jq_unavailable"
command -v "$GH_BIN" >/dev/null 2>&1 || emit_unavailable "gh_unavailable"

# ---- parse input ------------------------------------------------------------
RAW="${1:-}"
[ -n "$RAW" ] || emit_unavailable "bad_input"

REPO=""
NUMBER=""
case "$RAW" in
  https://github.com/*/*/pull/*|http://github.com/*/*/pull/*)
    # .../OWNER/REPO/pull/N  (tolerate a trailing slug/query/fragment after N)
    rest="${RAW#*github.com/}"
    OWNER="${rest%%/*}"; rest="${rest#*/}"
    REPONAME="${rest%%/*}"; rest="${rest#*/}"        # rest now starts with "pull/N..."
    rest="${rest#pull/}"
    NUMBER="${rest%%[/?#]*}"                          # strip any /, ?, # tail
    REPO="$OWNER/$REPONAME"
    ;;
  */*#*)
    # OWNER/REPO#N
    REPO="${RAW%%#*}"
    NUMBER="${RAW##*#}"
    ;;
  *)
    emit_unavailable "bad_input"
    ;;
esac

# Validate shape: REPO must be exactly owner/repo (one slash, both non-empty);
# NUMBER must be all digits and non-empty.
case "$REPO" in
  */*/*|/*|*/) emit_unavailable "bad_input" ;;
  */*) : ;;
  *)   emit_unavailable "bad_input" ;;
esac
[ -n "${REPO%%/*}" ] && [ -n "${REPO#*/}" ] || emit_unavailable "bad_input"
case "$NUMBER" in
  ''|*[!0-9]*) emit_unavailable "bad_input" ;;
esac

# ---- fetch PR core (single gh call) ----------------------------------------
# All field extraction is done from this one JSON blob to minimize gh round-trips.
# `gh pr view` resolves OWNER/REPO#N via --repo + the number argument.
PR_JSON="$("$GH_BIN" pr view "$NUMBER" --repo "$REPO" \
  --json number,title,body,additions,deletions,changedFiles,commits,reviews,statusCheckRollup \
  2>/dev/null)" || emit_unavailable "pr_inaccessible"

# Empty output or non-JSON => inaccessible/not-found.
[ -n "$PR_JSON" ] || emit_unavailable "pr_inaccessible"
printf '%s' "$PR_JSON" | jq -e . >/dev/null 2>&1 || emit_unavailable "pr_inaccessible"

# ---- fetch issue comments (second gh call, FAIL-SAFE) -----------------------
# Bot-posted CI review feedback lives in issue comments, not review objects (see
# header). One page of 100 is plenty for a churn trend signal. On ANY failure
# (gh error, empty output, non-array JSON) degrade to [] — the gatherer then
# behaves exactly as before this signal existed. Never aborts, never emits
# unavailable for a comment-fetch-only failure.
IC_JSON="$("$GH_BIN" api "repos/$REPO/issues/$NUMBER/comments?per_page=100" 2>/dev/null)" || IC_JSON="[]"
[ -n "$IC_JSON" ] || IC_JSON="[]"
printf '%s' "$IC_JSON" | jq -e 'type=="array"' >/dev/null 2>&1 || IC_JSON="[]"

# ---- build the normalized object (SINGLE jq invocation) --------------------
# All untrusted PR text (title, body, commit messages, review bodies, check names)
# is passed via --arg/--argjson and processed ENTIRELY inside the jq program. The
# heuristics (agent_generated_guess, is_review_fix, review_rounds) are computed in
# jq so no shell string-templating of PR text ever happens.
#
# ascii/control sanitation: snippets are truncated to 200 chars and control chars
# (incl. CR/LF/TAB) are replaced with a space via gsub, then collapsed.
OUTPUT="$(printf '%s' "$PR_JSON" | jq -c \
  --arg repo "$REPO" \
  --argjson number "$NUMBER" \
  --argjson issue_comments "$IC_JSON" \
  '
  # ---- heuristic regexes (case-insensitive) ----
  # NB: do NOT embed \uXXXX surrogate escapes in these regex strings — the jq regex
  # engine treats \u literally. The 🤖 robot-emoji marker is matched as a literal
  # below via a plain substring `contains`, not via a regex escape.
  # agent_commit_re is matched against commit SUBJECTS: "self-heal" anywhere, or a
  # subject-LEADING task-id ("bd-12a: …") / worktree-convention ("subtask: …") prefix.
  # Anchoring is deliberate — a bare word-dash-number pattern false-positives on
  # utf-8 / sha-256 / base-64. "co-authored-by" lives in agent_body_re (body trailer;
  # it can never appear in a subject line).
  def agent_body_re: "generated by supervisor|generated with claude code|co-authored-by: *claude";
  def agent_commit_re: "self-heal|^subtask: |^[a-z]{2,}-[0-9]+[a-z]?:";
  def review_fix_re: "address(es)? review|review feedback|fix review|self-heal|review comment";
  # bot_review_marker_re marks a bot ISSUE COMMENT as review-shaped: a markdown
  # heading containing "review", or the phrase "code review" (case-insensitive).
  # The "\n" here is a jq string escape producing a real newline char in the
  # regex — fine for Oniguruma (unlike \uXXXX, which jq regexes treat literally).
  def bot_review_marker_re: "(^|\n)#{1,6}[^\n]*review|code review";

  # ---- normalize a free-text snippet: strip control chars, collapse ws, cap 200 ----
  # POSIX classes (jq/Oniguruma): [[:cntrl:]] strips ALL control chars incl. CR/LF/TAB;
  # [[:space:]]+ then collapses runs of whitespace to a single space. (Do NOT use
  # \uXXXX char-class ranges here — the jq regex treats \u literally, which silently
  # turns the class into a huge codepoint range that eats ordinary letters.)
  def snippet:
    (. // "")
    | gsub("[[:cntrl:]]"; " ")
    | gsub("[[:space:]]+"; " ")
    | gsub("^ +| +$"; "")
    | if (length) > 200 then .[0:200] else . end;

  (.title // "")                as $title
  | (.body // "")               as $body
  | ([ .commits[]? | (.messageHeadline // (.message // "" | split("\n")[0]) // "") ]) as $headlines
  | ([ $headlines[] | { headline: ., is_review_fix: (test(review_fix_re; "i")) } ]) as $commits
  | ([ $commits[] | select(.is_review_fix) ] | length) as $review_fix_count
  # distinct CHURN-review submission timestamps — a review counts as churn only when
  # it requested changes, or commented with a non-empty body. Approval-only reviews
  # (APPROVED / bare LGTM) are NOT back-and-forth rounds and must not inflate the count.
  | ([ .reviews[]?
        | select( ((.state // "") == "CHANGES_REQUESTED")
                  or ( ((.state // "") == "COMMENTED")
                       and (((.body // "") | gsub("[[:space:]]+"; "")) != "") ) )
        | (.submittedAt // empty) ] | map(select(. != "" and . != null)) | unique | length) as $review_ts_count
  # bot-authored issue-comment review rounds (REST shape: .user.login / .created_at).
  # A round = a review-shaped bot comment with at least one commit AFTER it; ISO-8601
  # Z timestamps from both endpoints compare lexicographically.
  | ([ .commits[]? | (.committedDate // .authoredDate // empty) ]
     | map(select(. != null and . != ""))) as $commit_ts
  | ([ $issue_comments[]?
        | select( ((.user.login // "") | test("\\[bot\\]$"))
                  and ((.body // "") | test(bot_review_marker_re; "i")) ) ]) as $bot_reviews
  | ([ $bot_reviews[]
        | (.created_at // "") as $cts
        | select( $cts != "" and ([ $commit_ts[] | select(. > $cts) ] | length) > 0 ) ]
     | length) as $bot_round_count
  | ([$review_fix_count, $review_ts_count, $bot_round_count] | max) as $review_rounds
  # tie precedence fix_commits > formal_reviews > bot_comments — matches the
  # pre-existing two-signal MAX, which preferred the fix-commit count on ties.
  | (if $review_rounds == 0 then "none"
     elif $review_fix_count == $review_rounds then "fix_commits"
     elif $review_ts_count == $review_rounds then "formal_reviews"
     else "bot_comments" end) as $review_rounds_source
  | (([ .reviews[]?
        | select(((.body // "") | gsub("[[:space:]]+"; "")) != "")
        | { author: (.author.login // "unknown"), snippet: ((.body // "") | snippet) } ])
     + [ $bot_reviews[]
        | { author: (.user.login // "unknown"), snippet: ((.body // "") | snippet) } ]) as $review_comments
  # state fallthrough must skip empty strings, not just null: an in-progress CheckRun
  # has conclusion: "" (truthy in jq, so a bare // chain would stop there and surface
  # "" instead of falling through to .status == IN_PROGRESS).
  | ([ .statusCheckRollup[]?
        | { name: (.name // .context // "unknown"),
            state: ([ .state, .conclusion, .status ]
                    | map(select(. != null and . != "")) | (.[0] // "UNKNOWN")) } ]) as $ci_checks
  | (
      ($body | test(agent_body_re; "i"))
      or ($body | contains("🤖"))
      or ([ $headlines[] | test(agent_commit_re; "i") ] | any)
    ) as $agent_guess
  | {
      repo: $repo,
      number: $number,
      title: ($title | snippet),
      agent_generated_guess: $agent_guess,
      additions: (.additions // 0),
      deletions: (.deletions // 0),
      changed_files: (.changedFiles // 0),
      commits: $commits,
      review_rounds: $review_rounds,
      review_rounds_source: $review_rounds_source,
      review_comments: $review_comments,
      ci_checks: $ci_checks
    }
  ' 2>/dev/null)" || emit_unavailable "normalize_failed"

# Defensive: if jq produced nothing or invalid JSON, fall back to unavailable.
[ -n "$OUTPUT" ] || emit_unavailable "normalize_failed"
printf '%s' "$OUTPUT" | jq -e . >/dev/null 2>&1 || emit_unavailable "normalize_failed"

printf '%s\n' "$OUTPUT"
exit 0
