#!/usr/bin/env bash
# pr-postmortem-gather.sh — READ-ONLY PR data gatherer for /pr-postmortem (Subtask 1).
#
# Input: ONE PR reference, either
#   https://github.com/OWNER/REPO/pull/N    (full URL)
#   OWNER/REPO#N                            (short form)
#
# Output: exactly ONE normalized JSON object on stdout, jq-built (injection-safe).
# On success the object carries NO `status` field:
#   {
#     "repo": "owner/repo", "number": 42, "title": "...",
#     "agent_generated_guess": true,
#     "additions": 120, "deletions": 30, "changed_files": 5,
#     "commits": [{"headline": "...", "is_review_fix": false}],
#     "review_rounds": 3,
#     "review_rounds_source": "fix_commits",
#     "review_comments": [{"author": "...", "snippet": "..."}],
#     "ci_checks": [{"name": "...", "state": "SUCCESS"}]
#   }
#
# On ANY failure (gh/jq missing or unauthenticated, PR private/not-found/inaccessible,
# unparseable input) it emits a jq-built unavailable object and exits 0:
#   {"status":"unavailable","reason":"<short reason>"}
# The presence of `status` is how the caller distinguishes the two shapes.
#
# INVARIANTS (acceptance criteria):
#   1. ALWAYS exits 0. No `set -e` mid-emit crash; the script absorbs every failure.
#   2. The success JSON is built with a SINGLE jq invocation using --arg/--argjson
#      ONLY — no untrusted PR text is ever string-interpolated into JSON.
#   3. Pure read: no writes to the analyzed repo, no network beyond `gh`, no
#      mutating sub-process.
#
# TESTABILITY: every `gh` call goes through "$GH_BIN" (default `gh`). The self-test
# stubs `gh` by putting a fake earlier on PATH (so GH_BIN resolves to the stub); it
# does NOT need to override GH_BIN explicitly. GH_BIN exists as an extra override hook.
#
# HEURISTICS (documented per acceptance criteria):
#   agent_generated_guess — true if the PR body matches (case-insensitively) any of
#     "Generated by Supervisor", "Generated with Claude Code", "Co-Authored-By: Claude",
#     or contains the 🤖 robot emoji; OR if any commit subject mentions "self-heal" or
#     STARTS with an agent task-id prefix ("bd-12a: …") or the Supervisor's worktree
#     commit convention ("subtask: …"). The task-id pattern is deliberately anchored to
#     the subject-leading "id:" form — a bare word-dash-number match would false-positive
#     on ordinary tokens (utf-8, sha-256, base-64) and pollute the seed corpus this
#     trend data exists to build. ("Co-Authored-By" is a body trailer, so it is matched
#     against the PR body, never against commit subjects where it cannot appear.)
#     Best-effort signal, not authoritative.
#   commits[].is_review_fix — true if the commit subject matches (case-insensitively)
#     any of: "address review", "review feedback", "fix review", "self-heal",
#     "addresses review", "review comment", or the two EXPLICIT anchored forms
#     "pr #N review" / "review #N" (word-bounded — "preview #2" can never match).
#     A heuristic flag for review-churn commits. Deliberately NARROW: broadened
#     churn-word alternations ("nit", unanchored "round-N", "reconcil", "findings")
#     were evaluated and REJECTED as false-positive-prone (verified matches:
#     "background 4", "playground 2", "workaround 3", "reconcile inventory totals",
#     "add audit findings export"); the timestamp-anchored bot-round signal below
#     carries that undercount fix instead. The two explicit forms are NOT a
#     re-broadening to that rejected class: each requires the literal word "review"
#     adjacent to a PR/round number, covering headlines like "PR #146 review — …" /
#     "review #2 — …" (the HUB shape, vendsy/hub#146, verified 2026-06-10).
#   review_rounds — derived as MAX(count of is_review_fix commits, count of distinct
#     CHURN-review submission timestamps, count of timestamp-ANCHORED bot-review issue
#     comments). A review OBJECT counts as churn only when its state is
#     CHANGES_REQUESTED, or COMMENTED with a non-empty body — approval-only reviews
#     (APPROVED / bare LGTM) are NOT rounds of back-and-forth. A BOT-review issue
#     COMMENT counts as a round only when ALL of: (a) the author looks like a review
#     bot (login "claude", "github-actions", or any "*[bot]"); (b) its RAW body
#     carries a review MARKER — a word-bounded "review" ANYWHERE in the body
#     (originally a heading-anchored marker; widened because HUB-shape bot review
#     comments open with "## Overview" and mention review only in running text),
#     still word-bounded so "Deploy Preview" can never match; (c) at least one commit lands
#     AFTER the comment — comment `created_at` (REST, snake_case) vs commit
#     `committedDate` (gh pr view, camelCase), both ISO-8601 UTC so plain lexicographic
#     string comparison is correct. Anchoring keeps terminal "clean — recommend merge"
#     comments and re-reviews of unchanged pushes from inflating the count — but only
#     when nothing lands after the closer: a housekeeping commit (version bump, doc
#     tweak, rebase) AFTER an all-clear closer books one phantom round. Accepted
#     noise for a trend signal (true under the original heading-anchored marker too —
#     observed all-clear closers carry "## Review …" headings; a phrasing-based
#     negative anchor on "recommend merge"-style closers was considered and rejected
#     as brittle, the same class as the rejected churn words). CI review
#     workflows (e.g. claude-code-review.yml) post issue comments, NOT review objects,
#     so without this signal review_rounds reads 0 on exactly the repos this analyzer
#     targets (observed on PR #47: 0 review objects, 7 claude-bot review comments).
#     Comments come from a SECOND, separate, best-effort, read-only fetch
#     (`gh api repos/{owner}/{repo}/issues/{number}/comments?per_page=100`); on ANY
#     failure of that fetch (non-zero exit, empty output, non-JSON, non-array) the
#     script degrades to the two legacy signals and still emits the success shape —
#     NEVER an unavailable emit because of comments. The fetch is a bounded single
#     page (per_page=100, oldest-first; REST default would be 30): bot rounds past
#     comment #100 are dropped — accepted noise (`--paginate` would emit concatenated
#     arrays and break the single-value --argjson parse, silently degrading to []).
#     Using the max avoids undercounting when one signal is absent; caveats: several
#     fix commits inside a single round can still overcount, as can two reviewers
#     requesting changes within one logical round (distinct submittedAt) — accepted
#     noise for a trend signal.
#   review_rounds_source — names the dominant signal behind review_rounds:
#     "fix_commits" | "formal_reviews" | "bot_comments" | "none" (none when
#     review_rounds is 0; ties resolve in that order — the listed source is the
#     first signal whose count equals the max).

set -uo pipefail
# Intentionally NO `set -e`: the fail-safe JSON emit must never be aborted mid-stream.

GH_BIN="${GH_BIN:-gh}"

# ---- emit_unavailable <reason> ---------------------------------------------
# Emit the jq-built unavailable object and exit 0. Falls back to a hand-built
# minimal object only if jq itself is missing (reason is a fixed/whitelisted slug
# in that path, so no injection hazard). Always exits 0.
emit_unavailable() {
  local reason="$1"
  if command -v jq >/dev/null 2>&1; then
    jq -cn --arg reason "$reason" '{status:"unavailable", reason:$reason}'
  else
    # jq absent: reason here is always a fixed internal slug (no quotes/backslashes),
    # so direct interpolation is JSON-safe.
    printf '{"status":"unavailable","reason":"%s"}\n' "$reason"
  fi
  exit 0
}

# ---- tool availability ------------------------------------------------------
command -v jq >/dev/null 2>&1 || emit_unavailable "jq_unavailable"
command -v "$GH_BIN" >/dev/null 2>&1 || emit_unavailable "gh_unavailable"

# ---- parse input ------------------------------------------------------------
RAW="${1:-}"
[ -n "$RAW" ] || emit_unavailable "bad_input"

REPO=""
NUMBER=""
case "$RAW" in
  https://github.com/*/*/pull/*|http://github.com/*/*/pull/*)
    # .../OWNER/REPO/pull/N  (tolerate a trailing slug/query/fragment after N)
    rest="${RAW#*github.com/}"
    OWNER="${rest%%/*}"; rest="${rest#*/}"
    REPONAME="${rest%%/*}"; rest="${rest#*/}"        # rest now starts with "pull/N..."
    rest="${rest#pull/}"
    NUMBER="${rest%%[/?#]*}"                          # strip any /, ?, # tail
    REPO="$OWNER/$REPONAME"
    ;;
  */*#*)
    # OWNER/REPO#N
    REPO="${RAW%%#*}"
    NUMBER="${RAW##*#}"
    ;;
  *)
    emit_unavailable "bad_input"
    ;;
esac

# Validate shape: REPO must be exactly owner/repo (one slash, both non-empty);
# NUMBER must be all digits and non-empty.
case "$REPO" in
  */*/*|/*|*/) emit_unavailable "bad_input" ;;
  */*) : ;;
  *)   emit_unavailable "bad_input" ;;
esac
[ -n "${REPO%%/*}" ] && [ -n "${REPO#*/}" ] || emit_unavailable "bad_input"
case "$NUMBER" in
  ''|*[!0-9]*) emit_unavailable "bad_input" ;;
esac

# ---- fetch PR core (single load-bearing gh call) ----------------------------
# All field extraction is done from this one JSON blob to minimize gh round-trips.
# `gh pr view` resolves OWNER/REPO#N via --repo + the number argument.
PR_JSON="$("$GH_BIN" pr view "$NUMBER" --repo "$REPO" \
  --json number,title,body,additions,deletions,changedFiles,commits,reviews,statusCheckRollup \
  2>/dev/null)" || emit_unavailable "pr_inaccessible"

# Empty output or non-JSON => inaccessible/not-found.
[ -n "$PR_JSON" ] || emit_unavailable "pr_inaccessible"
printf '%s' "$PR_JSON" | jq -e . >/dev/null 2>&1 || emit_unavailable "pr_inaccessible"

# ---- fetch issue comments (SECOND, separate, best-effort, read-only fetch) --
# Bot review rounds live in ISSUE comments (REST shape: user.login / created_at /
# body), which `gh pr view --json` does not expose with timestamps. This fetch is
# fail-safe BY DESIGN and must stay out of the load-bearing call above: on ANY
# failure — non-zero exit, empty output, non-JSON output, non-array output — it
# degrades to '[]' so review_rounds falls back to the two legacy signals (review-fix
# commit headlines + formal churn-review submissions). A comments problem must NEVER
# turn the whole gather into an unavailable emit.
COMMENTS_JSON="$("$GH_BIN" api "repos/$REPO/issues/$NUMBER/comments?per_page=100" 2>/dev/null)" || COMMENTS_JSON='[]'
[ -n "$COMMENTS_JSON" ] || COMMENTS_JSON='[]'
printf '%s' "$COMMENTS_JSON" | jq -e 'type=="array"' >/dev/null 2>&1 || COMMENTS_JSON='[]'

# ---- build the normalized object (SINGLE jq invocation) --------------------
# All untrusted PR text (title, body, commit messages, review bodies, check names)
# is passed via --arg/--argjson and processed ENTIRELY inside the jq program. The
# heuristics (agent_generated_guess, is_review_fix, review_rounds) are computed in
# jq so no shell string-templating of PR text ever happens.
#
# ascii/control sanitation: snippets are truncated to 200 chars and control chars
# (incl. CR/LF/TAB) are replaced with a space via gsub, then collapsed.
OUTPUT="$(printf '%s' "$PR_JSON" | jq -c \
  --arg repo "$REPO" \
  --argjson number "$NUMBER" \
  --argjson comments "$COMMENTS_JSON" \
  '
  # ---- heuristic regexes (case-insensitive) ----
  # NB: do NOT embed \uXXXX surrogate escapes in these regex strings — the jq regex
  # engine treats \u literally. The 🤖 robot-emoji marker is matched as a literal
  # below via a plain substring `contains`, not via a regex escape.
  # agent_commit_re is matched against commit SUBJECTS: "self-heal" anywhere, or a
  # subject-LEADING task-id ("bd-12a: …") / worktree-convention ("subtask: …") prefix.
  # Anchoring is deliberate — a bare word-dash-number pattern false-positives on
  # utf-8 / sha-256 / base-64. "co-authored-by" lives in agent_body_re (body trailer;
  # it can never appear in a subject line).
  def agent_body_re: "generated by supervisor|generated with claude code|co-authored-by: *claude";
  def agent_commit_re: "self-heal|^subtask: |^[a-z]{2,}-[0-9]+[a-z]?:";
  # review_fix_re is deliberately NARROW (header doc): broadened churn-word
  # alternations (nit / unanchored round-N / reconcil / findings) were evaluated and
  # rejected as false-positive-prone; the anchored bot-round signal counts instead.
  # The two EXPLICIT anchored forms ("pr #N review" / "review #N") are not in that
  # rejected class: each carries the literal word "review" adjacent to a PR/round
  # number, word-bounded (\b) so "preview #2" can never match (no boundary inside
  # "preview"). They cover the HUB-shape headlines ("PR #146 review — …",
  # "review #2 — …") the narrow set missed (vendsy/hub#146, verified 2026-06-10).
  def review_fix_re: "address(es)? review|review feedback|fix review|self-heal|review comment|\\bpr #[0-9]+ review\\b|\\breview #[0-9]+\\b";
  # bot-review issue comments: CI review workflows (claude-code-review.yml et al.) post
  # ISSUE comments, not review objects — anchored ones are review rounds too (header doc).
  def bot_author_re: "^claude(\\[bot\\])?$|\\[bot\\]$|^github-actions";
  # review MARKER, tested against the RAW comment body: a word-bounded "review"
  # ANYWHERE in the body. Strict superset of the original v14.23.1 marker (markdown
  # heading containing "review", or the phrase "code review") — that heading-anchored
  # form missed the HUB shape, where claude-bot review comments open with
  # "## Overview" and mention review only in running text (vendsy/hub#146, verified
  # 2026-06-10). Word-bounded (\b, Oniguruma) so "preview"/"previews" — e.g. a
  # vercel[bot] "Deploy Preview for my-app ready!" notice — can never match
  # (test-pinned). False-round control now rests on the OTHER two gates, which are
  # unchanged: the author must look like a review bot AND a commit must land after
  # the comment (timestamp anchor). A non-review bot that merely says "review"
  # mid-PR is accepted noise for a trend signal (and only surfaces when the bot
  # count exceeds both legacy signals, since review_rounds takes the MAX).
  def review_marker_re: "\\breview\\b";

  # ---- normalize a free-text snippet: strip control chars, collapse ws, cap 200 ----
  # POSIX classes (jq/Oniguruma): [[:cntrl:]] strips ALL control chars incl. CR/LF/TAB;
  # [[:space:]]+ then collapses runs of whitespace to a single space. (Do NOT use
  # \uXXXX char-class ranges here — the jq regex treats \u literally, which silently
  # turns the class into a huge codepoint range that eats ordinary letters.)
  def snippet:
    (. // "")
    | gsub("[[:cntrl:]]"; " ")
    | gsub("[[:space:]]+"; " ")
    | gsub("^ +| +$"; "")
    | if (length) > 200 then .[0:200] else . end;

  (.title // "")                as $title
  | (.body // "")               as $body
  | ([ .commits[]? | (.messageHeadline // (.message // "" | split("\n")[0]) // "") ]) as $headlines
  | ([ $headlines[] | { headline: ., is_review_fix: (test(review_fix_re; "i")) } ]) as $commits
  | ([ $commits[] | select(.is_review_fix) ] | length) as $review_fix_count
  # distinct CHURN-review submission timestamps — a review counts as churn only when
  # it requested changes, or commented with a non-empty body. Approval-only reviews
  # (APPROVED / bare LGTM) are NOT back-and-forth rounds and must not inflate the count.
  | ([ .reviews[]?
        | select( ((.state // "") == "CHANGES_REQUESTED")
                  or ( ((.state // "") == "COMMENTED")
                       and (((.body // "") | gsub("[[:space:]]+"; "")) != "") ) )
        | (.submittedAt // empty) ] | map(select(. != "" and . != null)) | unique | length) as $review_ts_count
  # BOT-review ISSUE comments (third churn signal — see header doc). $comments is the
  # SECOND, best-effort fetch (REST shape: user.login / created_at / body; degraded to
  # [] on any fetch failure). A comment is a review COMMENT when the author looks like
  # a review bot AND the RAW body carries the review marker; it is a review ROUND only
  # when at least one commit lands AFTER it (created_at vs committedDate — both
  # ISO-8601 UTC, so plain lexicographic string comparison is correct). $comments is
  # validated only as "some array", so EVERY field access on a comment element is
  # double-guarded: the error-suppressing (…)? form absorbs path-access errors
  # (non-object parents) and `| strings` drops non-string VALUES so the // default
  # kicks in. The (…)? form ALONE is not enough: a non-string value (e.g.
  # {"user":{"login":123}}) exists and is truthy, survives //, and then type-errors
  # in test()/gsub() — aborting the SINGLE jq invocation and turning the whole gather
  # unavailable, which the header invariant forbids for any comments problem. With the
  # strings guard a hostile-typed element degrades to a non-match instead.
  | ([ .commits[]? | ((.committedDate)? // "") | select(. != "") ]) as $commit_dates
  | ([ $comments[]?
        | select( ((((.user.login)? | strings) // "") | test(bot_author_re; "i"))
                  and (((((.body)? | strings) // "") | gsub("[[:space:]]+"; "")) != "")
                  and ((((.body)? | strings) // "") | test(review_marker_re; "i")) ) ]) as $bot_review_comments_raw
  | ([ $bot_review_comments_raw[]
        | (((.created_at)? | strings) // "") as $cat
        | select( ($cat != "")
                  and ([ $commit_dates[] | select(. > $cat) ] | length > 0) ) ]) as $anchored_bot_rounds
  | ($anchored_bot_rounds | length) as $bot_round_count
  | ([ $review_fix_count, $review_ts_count, $bot_round_count ] | max) as $review_rounds
  # Dominant signal behind review_rounds; ties resolve fix_commits > formal_reviews
  # > bot_comments (first signal whose count equals the max), "none" when 0.
  | (if $review_rounds == 0 then "none"
     elif $review_fix_count == $review_rounds then "fix_commits"
     elif $review_ts_count == $review_rounds then "formal_reviews"
     else "bot_comments" end) as $review_rounds_source
  | ([ .reviews[]?
        | select(((.body // "") | gsub("[[:space:]]+"; "")) != "")
        | { author: (.author.login // "unknown"), snippet: ((.body // "") | snippet) } ]
     + [ $bot_review_comments_raw[]
        | { author: (((.user.login)? | strings) // "unknown"), snippet: ((((.body)? | strings) // "") | snippet) } ]) as $review_comments
  # state fallthrough must skip empty strings, not just null: an in-progress CheckRun
  # has conclusion: "" (truthy in jq, so a bare // chain would stop there and surface
  # "" instead of falling through to .status == IN_PROGRESS).
  | ([ .statusCheckRollup[]?
        | { name: (.name // .context // "unknown"),
            state: ([ .state, .conclusion, .status ]
                    | map(select(. != null and . != "")) | (.[0] // "UNKNOWN")) } ]) as $ci_checks
  | (
      ($body | test(agent_body_re; "i"))
      or ($body | contains("🤖"))
      or ([ $headlines[] | test(agent_commit_re; "i") ] | any)
    ) as $agent_guess
  | {
      repo: $repo,
      number: $number,
      title: ($title | snippet),
      agent_generated_guess: $agent_guess,
      additions: (.additions // 0),
      deletions: (.deletions // 0),
      changed_files: (.changedFiles // 0),
      commits: $commits,
      review_rounds: $review_rounds,
      review_rounds_source: $review_rounds_source,
      review_comments: $review_comments,
      ci_checks: $ci_checks
    }
  ' 2>/dev/null)" || emit_unavailable "normalize_failed"

# Defensive: if jq produced nothing or invalid JSON, fall back to unavailable.
[ -n "$OUTPUT" ] || emit_unavailable "normalize_failed"
printf '%s' "$OUTPUT" | jq -e . >/dev/null 2>&1 || emit_unavailable "normalize_failed"

printf '%s\n' "$OUTPUT"
exit 0
